import "./globals.css";
import Navbar from "@/components/Navbar";
import logo from "@/assets/images/logo.png";

export const metadata = {
  title: "Velvet Pour",
  description: "Generated by create next app",
  icons: {
    icon: logo.src,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={` h-full antialiased`}>
      <body className='min-h-500 flex flex-col'>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
